org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8
org.gradle.daemon=true
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
android.javaCompile.suppressSourceTargetDeprecationWarning=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
